version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET:-dev}
    env_file:
      - .env
    command: /entrypoint.sh
    ports:
      - "8000:8000"